package com.example

import android.accessibilityservice.AccessibilityService
import android.os.Bundle
import android.util.Log
import android.view.accessibility.AccessibilityEvent
import android.view.accessibility.AccessibilityNodeInfo
import java.util.concurrent.ConcurrentHashMap

class PurityAccessibilityService : AccessibilityService() {

    companion object {
        @Volatile
        var isAppWindowActive: Boolean = false
    }

    // A rolling cache of recently processed and replaced texts to completely prevent infinite cycles.
    private val processedCleanTexts = ConcurrentHashMap<String, Long>()

    // A rolling cache of recently processed raw (blocked) texts that we replaced, to prevent infinite battles with apps/IMEs.
    private val recentlyProcessedRawTexts = ConcurrentHashMap<String, Long>()

    override fun onAccessibilityEvent(event: AccessibilityEvent?) {
        if (event == null) return

        if (isAppWindowActive) {
            return
        }

        // Skip all events generated by our own application to prevent InputChannel crashes/deadlocks
        val eventPkg = try { event.packageName?.toString() } catch (e: Exception) { null }
        if (eventPkg == this.packageName || eventPkg == "com.example" || (eventPkg != null && eventPkg.contains("puritylock"))) {
            return
        }

        if (!PreferencesManager.isProtectionEnabled(this)) {
            return
        }

        val eventType = event.eventType
        if (eventType == AccessibilityEvent.TYPE_VIEW_TEXT_CHANGED || eventType == AccessibilityEvent.TYPE_VIEW_FOCUSED) {
            var isProcessed = false

            // 1. Process the direct source of the event info
            val source = try {
                event.source
            } catch (e: Exception) {
                null
            }
            if (source != null) {
                val isEditable = try { source.isEditable } catch (e: Exception) { false }
                if (isEditable) {
                    checkAndProcessNode(source)
                    isProcessed = true
                }
            }

            // 2. High-reliability fallback: process focused input field only if source wasn't processed
            if (!isProcessed) {
                val focusedNode = try {
                    findFocus(AccessibilityNodeInfo.FOCUS_INPUT)
                } catch (e: Exception) {
                    null
                }
                if (focusedNode != null) {
                    checkAndProcessNode(focusedNode)
                }
            }
        }
    }

    private fun checkAndProcessNode(node: AccessibilityNodeInfo?) {
        if (node == null) return

        if (isAppWindowActive) {
            return
        }

        // Do not process any node belonging to our own application to avoid interference and deadlock
        val nodePkg = try { node.packageName?.toString() } catch (e: Exception) { null }
        if (nodePkg == this.packageName || nodePkg == "com.example" || (nodePkg != null && nodePkg.contains("puritylock"))) {
            return
        }

        try {
            val isEditable = try {
                node.isEditable
            } catch (e: Exception) {
                false
            }

            if (isEditable) {
                processEditableNode(node)
            }
        } catch (e: Exception) {
            Log.e("PurityService", "Error during node safety check", e)
        }
    }

    private fun processEditableNode(source: AccessibilityNodeInfo) {
        try {
            val rawText = try {
                source.text
            } catch (e: Exception) {
                null
            } ?: return

            val currentText = rawText.toString()
            if (currentText.isEmpty()) return

            // Check loop and fight prevention caches
            if (shouldSkipProcessing(currentText)) {
                return
            }

            val blockedWords = PreferencesManager.getBlockedWords(this)
                .filter { it.isNotEmpty() }
                .sortedByDescending { it.length } // Longest first to cleanly eliminate compound adult phrases first!

            if (blockedWords.isEmpty()) return

            val caseInsensitive = PreferencesManager.isCaseInsensitive(this)
            val replacement = PreferencesManager.getReplacementText(this)

            var hasMatch = false
            var cleanText = currentText

            for (word in blockedWords) {
                if (caseInsensitive) {
                    if (cleanText.contains(word, ignoreCase = true)) {
                        hasMatch = true
                        cleanText = cleanText.replace(word, replacement, ignoreCase = true)
                    }
                } else {
                    if (cleanText.contains(word)) {
                        hasMatch = true
                        cleanText = cleanText.replace(word, replacement)
                    }
                }
            }

            // Only update text on actual match
            if (hasMatch && cleanText != currentText) {
                markTextAsProcessed(currentText, cleanText)

                val arguments = Bundle()
                arguments.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE, cleanText)
                
                val setSuccess = try {
                    source.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT, arguments)
                } catch (e: Exception) {
                    false
                }

                if (setSuccess) {
                    // Instantly snap the cursor position back to the end so input flows with absolutely zero lag
                    val selectionArgs = Bundle()
                    selectionArgs.putInt(AccessibilityNodeInfo.ACTION_ARGUMENT_SELECTION_START_INT, cleanText.length)
                    selectionArgs.putInt(AccessibilityNodeInfo.ACTION_ARGUMENT_SELECTION_END_INT, cleanText.length)
                    try {
                        source.performAction(AccessibilityNodeInfo.ACTION_SET_SELECTION, selectionArgs)
                    } catch (e: Exception) {
                        // Suppress selection action exceptions if the text field was closed
                    }
                }
            }
        } catch (e: Exception) {
            Log.e("PurityService", "Error during editable node processing", e)
        }
    }

    private fun shouldSkipProcessing(text: String): Boolean {
        val now = System.currentTimeMillis()

        // 1. Skip if we recently produced this exact text as a clean output (re-entry echo loop)
        val lastCleanTime = processedCleanTexts[text]
        if (lastCleanTime != null && (now - lastCleanTime < 2000)) {
            return true
        }

        // 2. Skip if we recently replaced this exact raw text (fight loop check)
        val lastRawTime = recentlyProcessedRawTexts[text]
        if (lastRawTime != null && (now - lastRawTime < 1500)) {
            return true
        }

        return false
    }

    private fun markTextAsProcessed(rawText: String, cleanText: String) {
        val now = System.currentTimeMillis()

        // Enforce max footprint cache size to keep battery and RAM usage practically zero
        if (processedCleanTexts.size > 20) {
            val iterator = processedCleanTexts.keys.iterator()
            if (iterator.hasNext()) {
                iterator.next()
                iterator.remove()
            }
        }
        processedCleanTexts[cleanText] = now

        // Enforce max footprint cache size on raw items
        if (recentlyProcessedRawTexts.size > 20) {
            val iterator = recentlyProcessedRawTexts.keys.iterator()
            if (iterator.hasNext()) {
                iterator.next()
                iterator.remove()
            }
        }
        recentlyProcessedRawTexts[rawText] = now
    }

    override fun onInterrupt() {
        Log.w("PurityService", "Purity Lock service interrupted by operating system")
    }

    override fun onServiceConnected() {
        super.onServiceConnected()
        Log.i("PurityService", "Purity Lock active shielding fully integrated and operational")
    }
}
